# Generated by Django 4.2.4 on 2023-10-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dada',
            name='text',
        ),
        migrations.AddField(
            model_name='dada',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
